services:
  - type: web
    name: proyecto-finanzas-backend-g6
    env: python
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements-simple.txt
    startCommand: uvicorn app_simple:app --host 0.0.0.0 --port $PORT

  - type: web
    name: proyecto-finanzas-g6
    env: static
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        value: https://proyecto-finanzas-backend-g6.onrender.com
      - key: VITE_API_URL
        value: https://proyecto-finanzas-backend-g6.onrender.com/api/v1
